In [1]:
import numpy as np
import pandas as pd
from os import listdir

In [2]:
save='val'

In [3]:
if save=='val': #for validation data
    path='train_additional' 
if save=='test':
    path='test'

In [4]:
classes=['wave', 'inf', 'eight', 'circle', 'beat3', 'beat4']
features=['time','Ax','Ay','Az','Wx','Wy','Wz']

In [5]:
centers=pd.read_csv('train_centers.csv')
display(centers.head())

          Ax        Ay        Az        Wx        Wy        Wz
0  -7.610235 -3.007808  3.427500 -0.340480  0.091003 -0.234542
1   7.703702  1.888134  9.910111  3.166512  0.403243  1.079956
2  -6.241958  2.581327  9.997086  3.312292 -2.269929 -2.058037
3 -10.394480  3.622676 -0.072113 -0.862464 -1.438293 -0.994525
4  -5.413195  3.936122  4.721623  0.396743 -0.347211  0.117283

In [6]:
ts_data={}

for i in listdir(path):
    
    df=pd.read_csv((path+'/'+i),header=None,sep='\t', lineterminator='\n')
    i=classes[np.where([x in i for x in classes])[0][0]]
    df=df.rename(columns=dict(enumerate(features)))
    df=df.drop(['time'],axis=1)
    
    if i in ts_data:
        ts_data[i]=ts_data[i].append(df,ignore_index=True)
    else:
        ts_data[i]=df

In [7]:
ts_data

{'beat3':            Ax        Ay        Az        Wx        Wy        Wz
 0    2.788223  7.051041  5.996323 -0.073151  0.069214  0.022049
 1    2.719193  7.096268  6.041550 -0.105194  0.081497  0.025253
 2    2.621597  7.010574  5.882065 -0.126556  0.099121  0.018845
 3    2.614456  6.932022  5.767807 -0.141510  0.114609  0.016174
 4    2.726334  6.760635  5.610703 -0.150055  0.115143  0.012436
 ..        ...       ...       ...       ...       ...       ...
 744  3.447586  0.081314 -2.377823  0.448090  0.070816  0.063705
 745  3.319046  0.067032 -2.546829  0.321518  0.084702  0.066376
 746  3.254776 -0.023422 -2.594437  0.192276  0.087906  0.072784
 747  3.133377 -0.094833 -2.670609  0.059296  0.088440  0.077591
 748  3.071487 -0.168625 -2.775345 -0.072617  0.089508  0.090942

 [749 rows x 6 columns],
 'beat4':            Ax        Ay        Az        Wx        Wy        Wz
 0    2.669205  9.207657  1.595016  0.121750  0.115982 -0.100128
 1    2.731094  9.193375  1.525986  0.108932  0.116516 -0.111343
 2    2.754898  9.157669  1.475998  0.092377  0.110107 -0.119354
 3    2.781082  9.112442  1.459335  0.085968  0.097290 -0.122559
 4    2.745377  9.045792  1.423630  0.075287  0.081802 -0.124161
 ..        ...       ...       ...       ...       ...       ...
 840  3.509476  1.331009 -4.717728  0.821899 -0.210861 -1.244614
 841  3.385696  1.414322 -4.615372  0.646194 -0.227417 -1.244614
 842  3.285721  1.545242 -4.484451  0.458206 -0.238098 -1.244080
 843  3.111954  1.590469 -4.434464  0.270218 -0.239166 -1.244080
 844  3.004837  1.673782 -4.436844  0.077423 -0.236496 -1.238739

 [845 rows x 6 columns],
 'circle':             Ax         Ay        Az        Wx        Wy        Wz
 0    -7.045090   3.609024  4.072983  0.167145 -0.006851 -0.151932
 1    -7.066513   3.628067  4.039658  0.178360 -0.005249 -0.150330
 2    -7.080795   3.625687  3.913498  0.187973 -0.006851 -0.149261
 3    -7.078415   3.711380  3.975388  0.198120 -0.007385 -0.150330
 4    -7.071274   3.692337  3.961105  0.209869 -0.005249 -0.150864
 ..         ...        ...       ...       ...       ...       ...
 623 -15.650131 -15.793381 -4.422562 -5.029236 -0.472015 -4.638016
 624 -16.054794 -16.109970 -4.684402 -5.103470 -0.342239 -4.646561
 625 -16.418991 -16.371811 -5.048599 -5.186249 -0.245041 -4.656708
 626 -16.735580 -16.705063 -5.541336 -5.266357 -0.187897 -4.665253
 627 -16.742722 -17.062119 -6.038834 -5.345932 -0.183090 -4.665787

 [628 rows x 6 columns],
 'eight':            Ax        Ay        Az        Wx        Wy        Wz
 0    7.030045  1.709488  8.141037 -0.127655 -0.139832 -0.060608
 1    7.113358  1.702347  8.086288 -0.149017 -0.107788 -0.041382
 2    7.144302  1.647598  8.098190 -0.166107 -0.072540 -0.016281
 3    7.120499  1.645218  8.014877 -0.182129 -0.031418  0.009888
 4    7.084793  1.735672  8.024399 -0.192810  0.010773  0.026978
 ..        ...       ...       ...       ...       ...       ...
 591 -3.767319 -9.847214 -4.817703  8.665070  1.960617  0.534866
 592 -3.631638 -9.854355 -4.510635  8.668808  1.545120  0.473450
 593 -3.465012 -9.806747 -4.094070  8.671478  1.167007  0.406158
 594 -3.024643 -9.737717 -3.637039  8.663467  0.830017  0.330322
 595 -2.858017 -9.766281 -3.039566  8.638367  0.540024  0.255554

 [596 rows x 6 columns],
 'inf':            Ax         Ay         Az        Wx        Wy        Wz
 0    6.849136   3.635208   6.524765  0.079025  0.095154  0.067566
 1    6.839615   3.597122   6.500961  0.058197  0.095154  0.068100
 2    6.849136   3.644730   6.539047  0.044846  0.097824  0.077179
 3    6.868179   3.589981   6.412888  0.030426  0.097290  0.085724
 4    6.915787   3.578079   6.391464  0.022949  0.102631  0.095337
 ..        ...        ...        ...       ...       ...       ...
 847  7.056229 -12.489426  12.958908 -1.631561 -0.851196 -6.981995
 848  7.429947 -12.472763  13.013657 -1.317535 -1.006607 -6.962769
 849  7.758438 -12.358505  13.235031 -1.015259 -1.137985 -6.918442
 850  7.967911 -12.260910  13.339767 -0.726868 -1.249603 -6.857025
 851  8.163101 -12.089523  13.175522 -0.459839 -1.343597 -6.781723

 [852 rows x 6 columns],
 'wave':            Ax        Ay        Az        Wx        Wy        Wz
 0    4.656815  5.698990  6.172470  0.230698  0.087677 -0.013077
 1    4.644913  5.687088  6.155807  0.226425  0.087677 -0.005066
 2    4.623489  5.722794  6.260544  0.218948  0.091949  0.003479
 3    4.563980  5.777542  6.262924  0.208801  0.094620  0.009888
 4    4.540176  5.765640  6.251022  0.196518  0.097290  0.014694
 ..        ...       ...       ...       ...       ...       ...
 436  1.064835  4.368362  5.108444  3.961624  2.340332 -3.134109
 437  0.926773  4.430252  5.041794  3.952545  2.367569 -3.033707
 438  0.879166  4.523087  4.884689  3.925842  2.366501 -2.927963
 439  0.676834  4.606400  4.825180  3.886856  2.348343 -2.821152
 440  0.633987  4.715897  4.689499  3.840393  2.311493 -2.715942

 [441 rows x 6 columns]}

In [8]:
def euclidean(A,B):
    return np.sqrt(np.sum((A - B)**2, axis=1))

In [9]:
def knn(data,centers):
    data=data.to_numpy(float)
    centers=centers.to_numpy(float)
    new = np.zeros((len(data)))
    for p in range(len(data)):
        new[p]=np.argmin(euclidean(data[p,:],centers))
         
    return new

In [10]:
ts_new = {}
for c in classes:
    ts_new[c]=pd.DataFrame(knn(ts_data[c],centers),columns=['centers'])
    ts_new[c].to_csv(save+'/'+c+'.csv',index=False)